### PR TITLE
add <title>

### PR DESCRIPTION
**Pull request by winny-**
Found this webpage super handy.  Added a bookmark, but found searching for dvorak in my bookmarks didn't yield this bookmark entry.

Adding a title with the correct key words might help with search-ability. 

thanks again for making this page :)

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
sounds good (even though it has been 9 months)

**Comment by winny-** [comment]
Sounds good, do we need somebody with contributor access to merge?

**Comment by ghost** [comment]
> Sounds good, do we need somebody with contributor access to merge?

<details>
<summary>Well yes, I just approved to I guess maybe liven up this pull request.</summary>
Only those with write access to this repository can merge pull requests.
</details>
Though if someone has Discord, maybe they can just link to this pull request.

**Comment by winny-** [comment]
I left a message on the Discord.  It appears Henri has left Discord recently, but maybe someone else there knows how to contact Henri.

**Comment by ghost** [comment]
I found the [YouTube channel](https://www.youtube.com/channel/UCsXf6lqmMTC0P7c5HPCgvVw) and it appears it is still active (1 week ago), I also found the [typeracer](https://data.typeracer.com/pit/profile?user=loboru), [twitch](https://www.twitch.tv/loboru/), [reddit](https://www.reddit.com/user/loboru/), [keyma.sh](https://keyma.sh/profile/loboru-1626) accounts.
(Ignore my stalking)

**Comment by winny-** [comment]
It looks like Looboru invited me to be a collaborator.  With your approval @GrpeApple I'll go ahead and merge this change.  I don't intend on doing additional work on this repository, but am happy to assist with clicking merge buttons, if this ever happens again =)

**Pull request merged**
